// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe9fgIrVGm_WA3GibZhPKT-Po6Us7fo0g',
    appId: '1:477086842169:web:47d86c5a9c3e66fd49bce8',
    messagingSenderId: '477086842169',
    projectId: 'test-d6f36',
    authDomain: 'test-d6f36.firebaseapp.com',
    storageBucket: 'test-d6f36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJAftkztJtYssTgIgRki4nzf-MSoo9xy8',
    appId: '1:477086842169:android:c4444cefd2642b6149bce8',
    messagingSenderId: '477086842169',
    projectId: 'test-d6f36',
    storageBucket: 'test-d6f36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr9QAYmP57c1geEJcw5u1rqvCu8okYpgw',
    appId: '1:477086842169:ios:cee12fe474c171d749bce8',
    messagingSenderId: '477086842169',
    projectId: 'test-d6f36',
    storageBucket: 'test-d6f36.appspot.com',
    iosClientId: '477086842169-k3snr5ouimlali34dk2l30r7hu2aera3.apps.googleusercontent.com',
    iosBundleId: 'com.example.theApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr9QAYmP57c1geEJcw5u1rqvCu8okYpgw',
    appId: '1:477086842169:ios:cee12fe474c171d749bce8',
    messagingSenderId: '477086842169',
    projectId: 'test-d6f36',
    storageBucket: 'test-d6f36.appspot.com',
    iosClientId: '477086842169-k3snr5ouimlali34dk2l30r7hu2aera3.apps.googleusercontent.com',
    iosBundleId: 'com.example.theApp',
  );
}
